networks:
  elastic:
    driver: bridge

volumes:
  db-data:

services:
  db:
    image: postgres
    restart: always
    user: postgres
    container_name: db
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=bandpal
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:?err}
    expose:
      - 5432
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - elastic
  app:
    container_name: app
    build:
      context: .
      target: dev
    environment:
      NODE_ENV: development
      POSTGRES_PRISMA_URL: "postgres://postgres:${POSTGRES_PASSWORD:?err}@db:5432/bandpal"
      WATCHPACK_POLLING: true
    command: pnpm dev
    ports:
      - 3000:3000
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    depends_on:
      - db
    networks:
      - elastic
  elasticsearch:
    image: elasticsearch:7.16.1
    container_name: es
    environment:
      discovery.type: single-node
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
      - "9300:9300"
    healthcheck:
      test: ["CMD-SHELL", "curl --silent --fail localhost:9200/_cluster/health || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 3
    networks:
      - elastic
  kibana:
    image: kibana:7.16.1
    container_name: kib
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    networks:
      - elastic