networks:
  bandpal:
    driver: bridge

volumes:
  db-data:
  data:

services:
  db:
    image: postgres
    restart: always
    user: postgres
    container_name: db
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=bandpal
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:?err}
    expose:
      - 5432
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - bandpal
  app:
    container_name: app
    build:
      context: .
      target: dev
    environment:
      NODE_ENV: development
      POSTGRES_PRISMA_URL: "postgres://postgres:${POSTGRES_PASSWORD:?err}@db:5432/bandpal"
      WATCHPACK_POLLING: true
    command: pnpm dev
    ports:
      - 3000:3000
    expose:
      - 3000
      - 3001
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    depends_on:
      - db
    networks:
      - bandpal