name = "bandpal"              
compatibility_date = "2025-08-29"

pages_build_output_dir = ".svelte-kit/cloudflare"

compatibility_flags = [ "nodejs_compat" ]

[[hyperdrive]]
binding = "HYPERDRIVE"
id = "f2c66017b221453d97df22aedf5fe811"