name: Deploy to Cloudflare
on:
  push:
    branches:
      # - main
      - development
  workflow_dispatch:

jobs:
  deploy:    
    environment: Production

    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      DATABASE_READ_URL: ${{ secrets.DATABASE_READ_URL }}
      AUTH_SECRET: ${{ secrets.AUTH_SECRET }}
      AUTH_GOOGLE_SECRET: ${{ secrets.AUTH_GOOGLE_SECRET }}
      AUTH_GOOGLE_ID: ${{ vars.AUTH_GOOGLE_ID }}

    runs-on: ubuntu-latest
    steps:
      - name: Set branch name
        run: |
          echo "BRANCH_NAME=${GITHUB_REF_NAME}" >> $GITHUB_ENV
          if [ "$GITHUB_REF_NAME" = "main" ]; then
            echo "ENVIRONMENT_NAME=Production" >> $GITHUB_ENV
          else
            echo "ENVIRONMENT_NAME=Development" >> $GITHUB_ENV
          fi

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Generate Prisma Client
        run: pnpm db:generate

      - name: Build project
        run: pnpm build

      - name: Publish to Cloudflare
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy --project-name=bandpal --branch=${{ env.BRANCH_NAME }}
       